### ISSUE TITLE
Error Code: 122 IDB-2006: 'schema.tablename' does not exist in InfiniDB

### ISSUE THREAD

**Issue by DevLu** [infinidb/infinidb#10]
Hi guys,

When I tried to access my tables in one of my schema's this morning, it gave me the above error. I've accessed it last week Friday without any issues. Is there a way to fix this? 
This is happening to all the tables in this schema. All the other schema's are fine. 
I'm running a InfiniDB version 4.6.0 on that server.

I've restarted the services and the server...no change.

Thanks

**Comment by brianrp** [comment]
Look for the datadir setting in the my.cnf file.
Go to that directory and look to see if the directory and tables files are there.

Connect to the database and run these queries:
use information_schema;
select count(*) from tables where TABLE_SCHEMA='<your missing schema>'  and engine='InfiniDB';

use calpontsys;
select count(*)from systable where `schema`='your missing schema';

Let me know what the results were.

**Comment by DevLu** [comment]
Thanks Bian,
my.cnf - > I can see all the tables for the schema
information_schema -> Count is 20 (same as the amount of tables for that schema)
I can still see the schema and all it's tables, its only happening to 11 of the 20 tables. The others are okay.
calpontsys -> Count is 15

Thanks

**Comment by brianrp** [comment]
Not what I thought was the possibility. (the mysql schema missing tables defined in calpontsys tables. A situation which may occur if you reload the software and the mysql datadir is moved.)
Make sure all the mounts are present on all nodes.
The count of tables in information_schema with engine='InfiniDB' should match the count of tables in the calponsys tables.
Check the log files. (The installation creates the alias 'log' to take you to their log directory.)
Look for any errors you can follow up on that might be related.
If you created any soft links to relocate directories to locations with more disk space, check the links.
If you don't find anything the only suggestion i have is to drop the affected tables, recreate and reload them.

**Comment by attaman** [comment]
I'm seeing the same error.
I tried what brianrp suggested in the first reply:
first query returned 43, all tables are there,
but second returned 0 - both systable and syscolumn tables are empty.

What do I do?!? Please hekp!!!
