### ISSUE TITLE
Bug report for Infinidb 4.6.2

### ISSUE THREAD

**Issue by tongsir** [infinidb/infinidb#11]
Hi there,
thank you for your great job on such a great data warehouse,
but during trying Infinidb, I found a situation which will lead data inconsistency with what it should be, below is the step for reproduce the bug.

mysql> create table t2 (c1 varchar(100), c2 varchar(100))engine=infinidb;
Query OK, 0 rows affected (13.23 sec)

mysql> insert into t2 values ("12345","12345"),("23456","23456"),("34567","34567");
Query OK, 3 rows affected (40.09 sec)

mysql> SELECT c1 FROM t2 WHERE t2.c1 LIKE CONCAT((IF('62101'='62101','1','2')),'%');
+-------+
| c1    |
+-------+
| 12345 |
| 23456 |
| 34567 |
+-------+
3 rows in set (0.03 sec)

you can see that when the result set should be '12345', but its outcome is not.

it seems this bug only occur when LIKE, CONCAT and IF is used together.

waiting for your reply at sitong@outlook.com :)

regards.

**Comment by tongsir** [comment]
Has anyone checked it? the bug should be fixed emergently cause it is the basic function.

**Comment by davidhilldallas** [comment]
Sorry, didn't catch this when it was originally posted. Did reproduce in latest version of 4.6 and opened an Internal MariaDB BUG.

Thanks for reporting..

**Comment by tongsir** [comment]
Is there a mail list for our external guys, and could i get the access to the bug report information of Infinidb ?

**Comment by davidhilldallas** [comment]
Nope, there is not a mail list for a bug reports for non InfiniDB Enterprise users. To become a Enterprise user, please contact MariaDB which provides support for InfiniDB Enterprise.

https://mariadb.com/services/infinidb-services

**Comment by tongsir** [comment]
So what is the schedule for next version of InfiniDB, with this bug fixed ? :)

**Comment by davidhilldallas** [comment]
We generally perform InfiniDB releases the last week of the month. This BUG has been fixed and is scheduled to be released at the end of this month.

**Comment by smagellan** [comment]
@davidhilldallas, what do you mean by 'perform InfiniDB releases'? I.e.: Are these new releases available for non-Enterprise users?

**Comment by davidhilldallas** [comment]
Thanks, 'schedule' is a better work. That is when we plan to do a QA on the builds and release to the public.

And yes, these builds are available to the public. Here is the procedure:

1. Create an account by clicking the "Sign Up" button from this WEB site:
   https://mariadb.com/blog/infinidb-support-continues-part-mariadbs-service-offering
2. Then after you log in, click "My Portal" button, top right, if you are already on the "My Portal" Page
3. Click Downloads on tab bar
4. Click InfiniDB, you should be on the InfiniDB page to select packages to download.

**Comment by smagellan** [comment]
Good, I just did expect to find release bundles on github, not mariadb.com. Thanks!
