### ISSUE TITLE
Latest Source Code

### ISSUE THREAD

**Issue by bhelm** [infinidb/infinidb#14]
Is it possible to get access to the source code of the latest version from Mariadb (4.6.4)? 
Im thinking about adding a ceph/librados storage option to infinidb and would like to do that on the latest version, as it contains some fixes for problems in version 4.6.2.

Thank you.

**Comment by bhelm** [comment]
Because of the WriteEngineServ crashes in #17 i would like to compile writeengine with debug symbols, but therefore i need the sourcecode. Will it be released? Thank You.

**Comment by tongsir** [comment]
@davidhilldallas , so is there a convenient way to get the latest source code? i do not get it from mariadb website :(
