### ISSUE TITLE
InfiniDB 4.6.2

### ISSUE THREAD

**Issue by tongsir** [infinidb/infinidb#16]
Hi,
It seems I have just found another bug of InfiniDB on version 4.6.2(other versions not tested.), please take a look.

<h4>
Bug Description:
</h4>

When using InfiniDB 4.6.2 to dynamically add a UM module, calpontConsole reports fail.

<pre>
calpont> addmodule um 1 172.16.110.25 abc123
addmodule   Wed Jun 8 11:36:57 2015

Adding Modules um2, please wait...

**** addModule Failed: API Failure return in addModule API
</pre>

while in the OAM's debug log, I did find that script binary_installer.sh was invoked by addModule command, I tried to execute the binary_installer.sh with the parameters listed in the debug log. It worked! A new UM finally add to the cluster without stop the cluster.

so, maybe there is a bug in calpontConsole to handle addModule command.

Regards and waiting for your reply :)

**Comment by davidhilldallas** [comment]
Thanks for reporting that. There was an BUG in the 4.6.2 where the addModule via the binary_installer would fail. Process-manager, the caller of the script didn't pass in the arguments corrects. That is why it worked when you tried it manually.

This BUG has been fixed and is in the latest build, 4.6.5..

**Comment by gao1738** [comment]
where I can download the latest build? such as 4.6.5?
