### ISSUE TITLE
CAL0002: Update Failed

### ISSUE THREAD

**Issue by lintrus** [infinidb/infinidb#18]
Hi, 

using InfiniDB 4.6.0 and trying to update a table (80 columns (mainly varchar), 1,5 millions "rows") I get an error. 
This update used to work well til now, with similar data quantities.

The exact error in error.log is : 

**Jul  7 14:12:25 cosmo dmlpackageproc[6856]: 25.004649 |0|0|0| E 21 CAL0002: Update Failed:   no space for a dictionary insert**

When I try to update only a subset of the 80 columns I get this error, seems to concern only a few columns among the 80 :

**Jul  7 14:09:06 cosmo Calpont[6793]: 06.156117 |0|0|0| E 00 CAL0000: we_dctnry.cpp@1120: assertion 'dbyte == BYTE_PER_BLOCK' failed  
Jul  7 14:09:06 cosmo writeengine[6793]: 06.156238 |0|0|0| E 19 CAL0001: we_readthread caught exception  IDB-2035: An internal error occurred.  Check the error log file & contact support.  
Jul  7 14:09:06 cosmo dmlpackageproc[6856]: 06.257900 |0|0|0| E 21 CAL0002: Update Failed:  CAL0001: we_readthread caught exception  IDB-2035: An internal error occurred.  Check the error log file & contact support.**  

I dropped the table and recreated it, but no effect.

Any idea ? 
Is there a way to increase space for dictionary ? But I don't know if this could be a solution. 

Thank you

Nicolas

**Comment by bhelm** [comment]
i had this bug today, but reloading the table resolved it (for now).

**Comment by lintrus** [comment]
Fortunately I resolved the problem too, but I don't know exaclty how ... I tried multiple "light" solutions among which recreate or reload the table several times, vary the way to update it, restart of the database, etc. ... and finally I didn't change anything and till now it works !
