### ISSUE TITLE
installed, but lack of infinidb storage engine

### ISSUE THREAD

**Issue by shanturen** [infinidb/infinidb#19]
i have a problem about installation. here is my step.
1, i get the source(infinidb & mysql)  from here, and follow the install step.
2, after the 2 make install, i got a directory named infinidb which was configured by --prefix.
3, i move the infinidb directory to /usr/local/Calpont
4, run /usr/local/Calpont/bin/post-install
5, run /usr/local/Calpont/bin/postConfigure
6, run canpontAlias
7 , all of the steps get no error, 

then i run idbmysql to try to use the infinidb engine, and i got the problem:
when i add engine=infinidb in my table creation statement, a warning printed, 
'show warnings' tells me that 'infinidb' is a unknown table engine, 
then i "select \* from information_schema.engines", it does has no "infinidb", but have "CSV,MRG_MYISAM,MEMORY,MyISAM', 

did i miss something during the installation?
i don't know what is going wrong,

**Comment by shanturen** [comment]
solved by download  bin package from maria,  this issues does't ma

**Comment by shanturen** [comment]
solved by download bin package from mariadb.com

**Comment by danyrlz** [comment]
Hello,

Would you let me know which package exactly did you download from mariadb?

Thanks in advance.

**Comment by davidhilldallas** [comment]
InfiniDB is released in 3 package forms, rpm, debian, and binary. Its up to
you know decide which of these packages you need to download and install
based on your OS or system setup. centos uses rpms, ubuntu/debian uses
debian, all os's and non-root user install use binary.

So install one of these from the InfiniDB Download portal page after you
login

On Thu, Sep 10, 2015 at 9:02 AM, danyrlz <notifications@github.com> wrote:

> Hello,
>
> Would you let me know which package exactly did you download from mariadb?
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/19#issuecomment-139243560>.
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by danyrlz** [comment]
I'm installing it from source and faced the same problem as shanturen.

Where can I find a deb package?
Thanks,

**Comment by davidhilldallas** [comment]
1. log into mariaDB with an account you have setup
2. Clink on "my portals" link top right
3. Click on Download button
4. Click on InfiniDB, takes you to the page where you can select which
package to download

You should end up here:

https://mariadb.com/my_portal/download/infinidb




On Thu, Sep 10, 2015 at 9:22 AM, danyrlz <notifications@github.com> wrote:

> I'm installing it from source and faced the same problem as shanturen.
>
> Where can I find a deb package?
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/19#issuecomment-139251519>.
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by sexygeoff** [comment]
I got this same problem installing from RPM :(
