### ISSUE TITLE
How to Speed Up, Other Than Via CPU

### ISSUE THREAD

**Issue by haimroman** [infinidb/infinidb#21]
We're trying to speed up performance, but hit a wall.  Our setup:

- Database size (for the tests)  is around 30GB, and about 800M records. 
- The query counts on all records by integer date, with an additional 4 columns on the filter.  
- we were using amazon instance C3.4Xlarge which had 16 cores, 30GB memory, and 2X160G SSD disks.

Results so far:
- The first time, the query takes about 43 seconds 
- consecutive query takes about 33 sec. It seems to be very slow, and we would like to speed up the results.
- for a single PM, going from 1 to 2 DBRoots didn't help.
- Going from a single PM to 2 PMs, each on a different machine, made the query a little more than twice as fast

The only way we've found so far to speed up is by increasing CPU power, but there is a limit on how much we can spend on this.  What else can be done to speed up these queries?

Thanks

**Comment by bhelm** [comment]
First make sure that you are hitting a CPU-Load limit. The query should use up all CPU resources available; if it is i.e. only using 80% if that, you may have io or network limiting the speed.
obviously, you will have best performance if your dataset fits into memory, if you have 30GB data and only 30GB memory on the machine, each query might have to read some data from the storage.
Also obvious, you can add more PMs until you get the desired performance, each pm memory will be added to infinidb's in-memory cache.

The biggest optimization potential comes from optimizing the query and optimizing the table structure, but this depends on the problem you want to solve. sometimes its possible to split the big table into smaller ones with pre-agregated data or into two tables that are queried separately and "joined" later. also choosing the correct datatypes is critical. you should read the infinidb documentation carefully, it gives a lot of hints on how stuff works and how to optimize for it. after understanding what each part of a query does within infinidb, i was able to optimize my data and queries, resulting in a 70% speedup.
without knowing your specific problem and data, i cant really give you a good advice.

it is also possible that there is a non-infinidb solution to you problem that fits your use-case better. i.e. for large scale time series data analysis there may be a more suitable software available, depending on your requirements.

**Comment by haimroman** [comment]
in the end, we moved to a cluster of 2 machines, each more powerful than the original.  But if we run into this problem again, we'll consider bhelm's answer.  Thanks.
