### ISSUE TITLE
Alter table to add column destroys table

### ISSUE THREAD

**Issue by sexygeoff** [infinidb/infinidb#25]
I am using InfiniDB 4.6.7. Two times I have added a column to a table and both times the table became corrupt. All data inserted into the table after the alter statement contained null values. I am able to insert rows, but every column is null. Data existing before the alter statement appears to be in tact. How can I avoid this from happening again?

I just tried to recreate the situation with a small table but was not able to. Maybe it only happens to tables containing millions of rows?

Does anybody have any suggestions on how I might save the existing data in a corrupt table?
(I'm trying a INSERT INTO good SELECT \* FROM bad)

**Comment by sexygeoff** [comment]
Maybe the problem is that I didn't follow the documentation. Here's what one is supposed to do:

> select calonlinealter('alter table foo add column col7 int;'); alter table foo add column col7 int comment 'schema sync only';

**Comment by bhelm** [comment]
right, good one. i did a alter table and "destroyed" it too. i'll try it next time that way.
