### ISSUE TITLE
Temp tables and Error Code: 122. fatal error executing query in crossengine client lib

### ISSUE THREAD

**Issue by sexygeoff** [infinidb/infinidb#29]
I believe I am getting this error because the query that causes it refers to a *temp* table and *temp* tables are not replicated across nodes in my 'combined' set up. Is my theory correct? The reason *temp* tables are used is because I'm using Tableau and Tableau relies on them in certain situations.

[This article](https://dev.mysql.com/doc/refman/5.1/en/replication-features-temptables.html) discusses temp table replication in MySql and suggests it is possible. Would this be a solution to my problem? I'm hesitant to mess with the replication settings. Also, I read somewhere that even if temp tables are replicated, they are only accessible by the thread that created them.

Thoughts?

InfiniDB 4.6.7
2 node cluster in 'combined' mode

**Comment by bhelm** [comment]
Hm, refering to the mysql documentation, statement-based replication should be the default and used if you have enabled replication with the postConfigure procedure. therefore temp tables should be subject to the one-way master-slave replication, so if you create on on the master node, it should be replicated to the slave.

Temp tables are temporary and do only exist within the current SQL session and will not be accessable from other concurrent sessions, even of the same user. so replication of temp tables does only allow you to replicate SQL-statements to the slaves that require those tables. so there is _no way_ to access the temp table on the slave directly. i think that is what is happening on a crossengine query, the table is not accessable.

if you want to make a result set accessable on all nodes, you have to create a normal table. But you have some choices, i.e. you can create the table with ENGINE=MEMORY and a temp-name which would perform like a temptable but will be accessable from all sessions until server restart.
be aware that if the slave restarts, it will have this table empty while the master will still have its contents. if the master then updates a record that is not existend on the slave, replication will fail.

**Comment by sexygeoff** [comment]
Hmm, I might just try to use MySQL proxy to rewrite Tableau queries creating and referencing temp table and make them real tables. I'm already using MySQL proxy to rewrite queries that use the ```<=>``` operator, which causes errors in InfiniDB, so as to use ```=``` instead.
