### ISSUE TITLE
 IDB-2003: Aggregation/Distinct memory limit is exceeded. 

### ISSUE THREAD

**Issue by XtreamData** [infinidb/infinidb#31]
Good day all.

When running a query like below I get this error. Any idea how to fix it?
It used to run  withing 7 secs but now after 10 secs this error comes up.

_select prod_cde,acct_no,count(distinct acct_no)
from fct.fct_dbanking_trans_new_dly
where ucn is not null
and prod_cde is not null
group by 1,2
having count(distinct acct_no) > 1
limit 20_

Infinidb Version: 4.6.7
2 x UM (32 cpu, 132G ram each)
4 x PM (32 cpu, 132G ram each)

Any input welcome please.
Frik Lubbe

**Comment by brianrp** [comment]
Not certain this is the correct setting for you, but it’s the only one I ever 'had' to add to the my.cnf file.

max_length_for_sort_data = 8388608

That’s the max value, you may want to choose a lower appropriate value for your situation.

Brian Pontius

**Comment by smagellan** [comment]
...or you can tune it via query: 'set max_length_for_sort_data = 8388608' (affects current session only)
