### ISSUE TITLE
Network Error Caused InfiniDB to become "read only"

### ISSUE THREAD

**Issue by haimroman** [infinidb/infinidb#32]
Setup:
- 2 Amazon c3.4xlarge machines.   One is "pm1" also includes the UM.  The other is "pm2" (no UM).
- They are _not_ on the same VPC.
- Pm1 runs Ubuntu 14.04.1 LTS.  Pm2 runs Ubuntu 14.04.4 LTS.
- Both run Linux kernel 3.13.0-44-generic.
- InfiniDB 4.6.0, release 1

We run cpimport a lot, as part of scheduled jobs.  At some point, it started printing the following messages:

```
2016-02-24 05:14:44 (103526) ERR  : Error: System in ReadOnly state
Failed to import file: customer_settings.tbl in /usr/local/Calpont/data/bulk/data/import
```

I found out that this started shortly after we had a network error between our machines:

```
Feb 24 00:04:13 pm1 ProcessManager[115661]: 13.420646 |0|0|0| W 17 CAL0000: NIC failed to respond to ping: 10.203.138.168         
Feb 24 00:04:13 pm1 ProcessManager[115661]: 13.451784 |0|0|0| W 17 CAL0000: module failed to respond to pings: pm2         
Feb 24 00:04:16 pm1 ProcessManager[115661]: 16.475738 |0|0|0| E 17 CAL0000: line: 3880 EXCEPTION ERROR on getProcessStatus: API Failure return in getProcessStatus API       
Feb 24 00:05:14 pm1 controllernode[116075]: 14.996679 |0|0|0| C 29 CAL0000: DBRM Controller: undo(): warning, could not contact worker number 2#012         
Feb 24 00:05:15 pm1 controllernode[116075]: 15.357412 |0|0|0| C 29 CAL0000: DBRM Controller: network error distributing command to worker 2#012         
...
Feb 24 00:05:16 pm1 writeenginesplit[53547]: 16.871048 |0|0|0| E 33 CAL0000: Error: System in ReadOnly state.         
Feb 24 00:05:16 pm1 writeenginesplit[53547]: 16.871266 |0|0|0| E 33 CAL0087: BulkLoad Error: Error: System in ReadOnly state.
```

("pm1" represents the host name of pm1)
The last 2 messages repeated _a lot_
**_Is there any way to make InfiniDB recover from short network problems?**_
Thanks

**Comment by bhelm** [comment]
normally, infinidb is resistant (and self-recovering) agains networking problems and process crashes.
if your installation is still in the read-only state, can you run "cc getsysteminfo" ? if something failed, it could be visible there.

in theoriy, if pm2 is unreachable, pm1 should mount its data dirs and should continue operation. when pm2 comes back available, it has to be migrated back manually. in reality, this does not always work reliable, but this depends a good bit on the actual setup and storage mounting.
if there really were a pm2 failure that infinidb tried to handle, there should be a lot more debug output. actually, if one pm fails, infinidb shuts down and restarts in single-pm mode which should give you some hundred lines of debug.

i can also recommended to upgrade to the latest infinidb version (4.6.7 currently) from mariadb, as it contains a lot of fixes which make infinidb more reliable. this may not fix exactly this problem, but some others you may run into. be sure to have a backup before upgrade and test the upgrade process on a non-production environment if possible.

**Comment by haimroman** [comment]
bhelm, thanks for your reply

- pm1 cannot mount pm2's data dirs, because we're not using external storage.  
- we'll consider the upgrade.
- I'll check the logs more.

Again, thanks.

**Comment by haimroman** [comment]
Since then, the pair of NIC & ping error messages has been logged a few times.  Here is an example where we see the communication recovering.  

```Feb 25 10:11:24 idb02-spa ProcessManager[8847]: 24.296194 |0|0|0| W 17 CAL0000: NIC failed to respond to ping: 10.203.138.168         
Feb 25 10:11:24 idb02-spa ProcessManager[8847]: 24.296250 |0|0|0| D 17 CAL0000: Set NIC 10.203.138.168 State = 9         
Feb 25 10:11:24 idb02-spa ProcessMonitor[8757]: 24.296416 |0|0|0| D 18 CAL0000: statusControl: REQUEST RECEIVED: Set NIC 10.203.138.168 State = DOWN         
Feb 25 10:11:24 idb02-spa ProcessManager[8847]: 24.327422 |0|0|0| W 17 CAL0000: module failed to respond to pings: pm2         
Feb 25 10:11:25 idb02-spa ProcessManager[8847]: 25.395589 |0|0|0| D 17 CAL0000: Set NIC 10.203.138.168 State = 8         
Feb 25 10:11:25 idb02-spa ProcessMonitor[8757]: 25.395787 |0|0|0| D 18 CAL0000: statusControl: REQUEST RECEIVED: Set NIC 10.203.138.168 State = UP
```

The point is, we haven't had the readonly error messages since.  

One thing I forgot was another error message that appeared a lot until while we had the readonly problem:

```
Feb 24 06:38:44 idb02-spa IDBFile[116326]: 44.201529 |0|0|0| E 35 CAL0002: Failed to open file: /000.dir/000.dir/019.dir/194.dir/000.dir/FILE004.cdf, exception: unable to open Unbuffered file  
```

**Comment by haimroman** [comment]
While looking into this, I found the following Calpont parameters that *might* be relevant:

```
Installation.AmazonSubNetID = unassigned

NetworkCompression.Enabled = Y

SystemConfig.DBRMTimeOut = 20
SystemConfig.ModuleHeartbeatCount = 3
SystemConfig.ModuleHeartbeatPeriod = 1
SystemConfig.ModuleProcMonWaitCount = 30
SystemConfig.WaitPeriod = 10

PrimitiveServers.DebugLevel = 3  
```

Questions:
1. Where can I read more about what each of these parameters do?
1. Anyone have any experience tweaking these parameters on multi-server systems?

Thanks
