### ISSUE TITLE
Documentation on all the Calpont parameters

### ISSUE THREAD

**Issue by haimroman** [infinidb/infinidb#33]
The command `/usr/local/Calpont/bin/getConfig -a` shows you all the Calpont parameters.  But where can I find documentation on what each one does?

**Comment by davidhilldallas** [comment]
here is an example, the first part is the bottom part of Calpont.xml

	<QueryTele>
		<Host>127.0.0.1</Host>
		<Port>0</Port>
	</QueryTele>
</Calpont>

# /usr/local/Calpont/bin/getConfig QueryTele Host
127.0.0.1
#
