### ISSUE TITLE
calShowPartitions datetime values N/A

### ISSUE THREAD

**Issue by danyrlz** [infinidb/infinidb#34]
Hello,

We're having 2 infinidb tables with the same structure. There is one app that inserts data in both tables.
The problem is that when we use calShowPartitions there are no MIN/MAX values for one of the tables. Here is the structure of the tables:

_+----------------+------------+------+-----+---------+-------+
| Field          | Type       | Null | Key | Default | Extra |
+----------------+------------+------+-----+---------+-------+
...........
| stamp_inserted | datetime   | YES  |     | NULL    |       |
| stamp_updated  | datetime   | YES  |     | NULL    |       |
+----------------+------------+------+-----+---------+-------+_

Here is the output for the first table. You can see the missing values:

_mysql> select calShowPartitions('table1','stamp_inserted');
| Part#     Min                           Max                           Status
  0.0.1     2016-01-18 19:00:00           2016-01-31 20:00:00           Enabled
  0.1.1     2016-01-21 11:00:00           2016-02-03 20:00:00           Enabled
  0.2.1     2016-01-24 00:00:00           2016-02-06 11:00:00           Enabled
  0.3.1     2016-01-26 16:00:00           2016-02-09 01:00:00           Enabled
  1.0.1     2016-02-09 01:00:00           2016-02-11 20:00:00           Enabled
  1.1.1     N/A                           N/A                           Enabled
  1.2.1     N/A                           N/A                           Enabled
  1.3.1     N/A                           N/A                           Enabled
  2.0.1     N/A                           N/A                           Enabled
  2.1.1     N/A                           N/A                           Enabled
  2.2.1     N/A                           N/A                           Enabled |_

Here is the output for the second table. All values are fine:

_mysql> select calShowPartitions('table2','stamp_inserted');
| Part#     Min                           Max                           Status
  0.0.1     2016-01-18 19:15:00           2016-01-22 18:35:00           Enabled
  0.1.1     2016-01-19 14:45:00           2016-01-23 13:40:00           Enabled
  0.2.1     2016-01-20 10:30:00           2016-01-24 07:25:00           Enabled
  0.3.1     2016-01-21 04:00:00           2016-01-24 22:40:00           Enabled
  1.0.1     2016-01-24 22:40:00           2016-01-28 21:20:00           Enabled
  1.1.1     2016-01-25 18:30:00           2016-01-29 18:20:00           Enabled
  1.2.1     2016-01-26 14:20:00           2016-01-30 13:45:00           Enabled
  1.3.1     2016-01-27 08:55:00           2016-01-31 08:05:00           Enabled
  2.0.1     2016-01-31 08:05:00           2016-02-04 13:55:00           Enabled
  2.1.1     2016-01-31 23:20:00           2016-02-05 08:50:00           Enabled
  2.2.1     2016-02-01 19:20:00           2016-02-06 00:30:00           Enabled
  2.3.1     2016-02-02 15:05:00           2016-02-06 20:40:00           Enabled
  3.0.1     2016-02-06 20:40:00           2016-02-10 20:50:00           Enabled
  3.1.1     2016-02-07 15:55:00           2016-02-11 18:20:00           Enabled
  3.2.1     2016-02-08 11:40:00           2016-02-12 14:40:00           Enabled
  3.3.1     2016-02-09 05:20:00           2016-02-13 10:40:00           Enabled
  4.0.1     2016-02-13 10:40:00           2016-02-17 12:55:00           Enabled
  4.1.1     2016-02-14 02:55:00           2016-02-18 09:00:00           Enabled
  4.2.1     2016-02-14 21:45:00           2016-02-19 01:40:00           Enabled
  4.3.1     2016-02-15 18:45:00           2016-02-19 21:25:00           Enabled
  5.0.1     2016-02-19 21:25:00           2016-02-23 22:05:00           Enabled
  5.1.1     2016-02-20 17:35:00           2016-02-24 19:00:00           Enabled
  5.2.1     2016-02-21 13:20:00           2016-02-25 15:35:00           Enabled
  5.3.1     2016-02-22 08:30:00           2016-02-26 11:30:00           Enabled
  6.0.1     2016-02-26 11:30:00           2016-03-01 11:00:00           Enabled
  6.1.1     2016-02-27 05:10:00           2016-03-02 05:15:00           Enabled
  6.2.1     2016-02-27 22:55:00           2016-03-02 22:50:00           Enabled
  6.3.1     2016-02-28 18:50:00           2016-03-03 19:00:00           Enabled
  7.0.1     2016-03-03 19:00:00           2016-03-04 14:55:00           Enabled
  7.1.1     2016-03-04 14:55:00           2016-03-05 10:25:00           Enabled
  7.2.1     2016-03-05 10:25:00           2016-03-06 03:50:00           Enabled
  7.3.1     2016-03-06 03:50:00           2016-03-06 22:00:00           Enabled |
_

Any ideas what may cause this behavior? All data and datetime values are correct in both tables.
Occasionally the real date values appear at some of the N/A lines but in most cases this issue occurs at a given partition and all the following partitions are affected.

**Comment by bhelm** [comment]
the partition min/max values are not determined on insertion/update time, they are collected on the first full partion scan.
issue a select on the datetime column like 
`select max(stamp_inserted) from table2`
and the values should show up in calShowPartitions.

**Comment by danyrlz** [comment]
Thank you for your answer.

Is this full partition scan automatically issued? In what period should it happen?
In my example there are 6 partitions that have not been scanned for up to 1 month period.

**Comment by bhelm** [comment]
it is not automatically (not a cron job or something), it happens at the first SELECT statement that uses this column. so if you want to see the correct min/max values in calShowPartitions, you have to do a SELECT on that column first.

try this:
```
select calShowPartitions('table1','stamp_inserted'); -- result has N/A values
select max(stamp_inserted) from table1; -- this select scanns the whole column
select calShowPartitions('table1','stamp_inserted'); -- now the N/A values should be gone
```
