### ISSUE TITLE
where I can download the latest infinidb version?

### ISSUE THREAD

**Issue by gao1738** [infinidb/infinidb#35]
Hi all,

It seams that the mariadb does not maintain the infinidb any more.
I find the http://infinidb.co/ , but there is no places for download or login.
And the github version is only 4.6.2.

where I can download the latest infinidb version or code?

dennis

**Comment by bhelm** [comment]
Version 4.6.7 is still available at Mariadb. Register a MariaDB account and then visit https://mariadb.com/my_portal/download/infinidb for binary and documentation download.

**Comment by gao1738** [comment]
@bhelm 
thank you very much!

Does mariadb will continue to maintain the infinidb or not?
If not, is there any guys going to maintain it or not?

Does mariadb plan to integate the infinidb into mariadb server as a engine or not?

dennis

**Comment by bhelm** [comment]
After the original infinidb company (Calpont) went bankrupt, mariadb took over their enterprise customer contracts. after the takeover i have read that integrating infinidb into mariadb as storage engine is possibly somewhere down the roadmap, but not a priority. some months after the takeover there also were a infinidb subsection on the "products" section of their main website, so i guess they were really about to continue the infinidb development as one of the primary mariadb projects. this page disappeared some months later. this will surely mean something, most likely nothing good.

mariadb took over the enterprise customers, and im sure they are the primary reason we have seen 5 InfiniDB releases from mariadb. I also think we will see some more bugfix-releases in the future, as long as the enterprise customers demand them. there is no release cycle, so time between releases can vary up to some months. its also a nice move from them to offer the infinidb binary packages to all registered users.
they will continue to maintain infinidb with some bugfixes their enterprise customers demand, but there are currently no signs that they have greater plans with it (adding new features, integrating to mariadb, its still possible they are doing this in the background, but i dont think so).

you can still ask them to offer enterprise support to you, just be prepared that this will require some budget.

sadly, there is not much activity on this bugtracker from the community either. i think mariadb will offer the latest sourcecode when asked for, but i have not seen any people here that were willing to actually do some patches themselfes. this makes me sad, as i feel that infinidb is a nice piece of technology. the mysql compatibility is a killer feature, as it allows you to sync large mariadb tables over to infinidb and query your data in light speed, what would not be possible by using mariadb only - and without modifying the queries of your application.
as i like infinidb (and have it running in production for a year), i will also sit here in the future and try to answer every ticket that pops up.

if you decide to use infinidb, be prepared that there are still bugs left (like #30  , #17 ). using infinidb is about learning what NOT to do. :)

still, i hope i can welcome you to our 3-man community soon :)

**Comment by brianrp** [comment]
I started using InfiniDB in production starting with version 2.0.2 in early 2011. The upgrades have all gone very well and I'm currently using version 4.6.7-1 from MariaDB.
MariaDB has redesigned their web page, that’s why the old link disappeared. They have good things currently in development, you can find it now under Products -> MariaDB ColumnStore. I don't know what the name change means for this site. But they clearly have plans for the future. There is currently a link on this web page to sign up for its beta release.
I am very pleased with its performance, compatibility with MySQL and the speed of data imports using cpimport is nothing less than fantastic.

I watch the activity here and correspond when and where I can help, but the engineers at MariaDB have been, up to know at least, watching activity and answering the harder questions.

I have looked at other solutions for our data set from time to time. I have not found anything else that provides the flexibility of data imports, query performance, low maintenance and scalability all in one product as is available with InfninDB. Not even Amazon Redshift, which is probably the next closest thing at the moment, in my opinion.

**Comment by bhelm** [comment]
Oh, thanks for the pointer to the MariaDB ColumnStore page. Sounds indeed like InfiniDB. i will wait eagerly, hope they will release something :)

**Comment by davidhilldallas** [comment]
Correct, MariaDB is coming out with a StoreColumn version of their product
which uses the InfiniDB open source software as it's core platform with the
MariaDB front-end. A beta version is planned for the next month or so.

On Thu, Apr 14, 2016 at 7:31 AM, Bernd Helm <notifications@github.com>
wrote:

> Oh, thanks for the pointer to the MariaDB ColumnStore page. Sounds indeed
> like InfiniDB. i will wait eagerly, hope they will release something :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/35#issuecomment-209915340>
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by gao1738** [comment]
Thanks!
Really happy to hear that MariaDB will going to integrate the infinidb into mariadb server :）

**Comment by chenxinglong** [comment]
I want to know, if the StoreColumn version come up with MariaDB 10 or higher?

**Comment by davidhilldallas** [comment]
MariaDB ColumnStore, which is using InfiniDB as the base platform and
MariaDB 10.01 as the mysql front-end.

On Wed, Apr 20, 2016 at 10:34 AM, chenxinglong <notifications@github.com>
wrote:

> I want to know, if the StoreColumn version come up with MariaDB 10 or
> higher?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/35#issuecomment-212480103>
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by chenxinglong** [comment]
How long will release? I'm waiting for the new version.

**Comment by bhelm** [comment]
im also kind of hyped :)

**Comment by davidhilldallas** [comment]
You can get more info here:

  https://mariadb.com/products/mariadb-columnstore

The Planned Beta is still a month or so away, so probably GA planned in mid
to late summer.

On Thu, Apr 21, 2016 at 3:55 AM, Bernd Helm <notifications@github.com>
wrote:

> im also kind of hyped :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/35#issuecomment-212818855>
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com
