### ISSUE TITLE
InfiniDB Port Numbers

### ISSUE THREAD

**Issue by XtreamData** [infinidb/infinidb#36]
Good day all,

I need some insight please. The standard port number for MySQL-InfiniDB is 3306. Where do I change the port number to what I need it to be, say... 3377?

Calpont.xml?
my.cnf?
Both?

Tx
Frik

**Comment by davidhilldallas** [comment]
if just running on a single node with no plans to expand to multi-nodes,
then just change my.cnf. But if you where to expand and you want to use the
same port on the other nodes, then change both.

On Mon, Apr 18, 2016 at 1:59 PM, XtreamData <notifications@github.com>
wrote:

> Good day all,
>
> I need some insight please. The standard port number for MySQL-InfiniDB is
> 3306. Where do I change the port number to what I need it to be, say...
> 3377?
>
> Calpont.xml?
> my.cnf?
> Both?
>
> Tx
> Frik
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/36>
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by XtreamData** [comment]
Thanks David. 
In a multi node cluster, do I only change these files on the primary OAM pm? 
Will it 'replicate' to the other nodes on system restart?

F

**Comment by davidhilldallas** [comment]
You will want to make the change on all existing nodes that have mysql
installed, so that would be a UM or a combo UM/PM for the my.cnf. That file
is not distributed to other nodes from pm1. But Calpont.xml only needs to
be changed on pm1, because updates there are distributed to all other nodes
when system restart time.

On Mon, Apr 18, 2016 at 2:28 PM, XtreamData <notifications@github.com>
wrote:

> Thanks David.
> In a multi node cluster, do I only change these files on the primary OAM
> pm?
> Will it 'replicate' to the other nodes on system restart?
>
> F
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/36#issuecomment-211541451>
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by XtreamData** [comment]
Final Question: I'm using v4.6.7Ent, will the MySQL replication for the catalog use the same port?

**Comment by davidhilldallas** [comment]
Actually that I don't know the answer to.. I don't know if mysql
replication uses the same port as the mysql connection port..

On Mon, Apr 18, 2016 at 2:35 PM, XtreamData <notifications@github.com>
wrote:

> Final Question: I'm using v4.6.7Ent, will the MySQL replication for the
> catalog use the same port?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/36#issuecomment-211543312>
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com
