### ISSUE TITLE
Error Code: 122 Lost connection to DDLProc during Alter Table

### ISSUE THREAD

**Issue by sexygeoff** [infinidb/infinidb#37]
Hi,

I'm getting the following error when attempting to alter a table as follows: `select calonlinealter("alter table table_name add column id bigint comment 'autoincrement,2147183537';");`

Error after just 10 seconds: `Error Code: 122 Lost connection to DDLProc`

Output from `./viewtablelock`:

```
There is 1 table lock
  Table         LockID  Process  PID    Session  Txn   CreationTime              State    DBRoots  
  bi.table_name  6       DDLProc  30020  14       2593  Tue Apr 19 23:07:29 2016  LOADING  1,2
```

The table has 1.6 billion rows. The storage is local to each node and uses SSD drives. Do I just need to wait longer? How can I tell if anything is happening? I've made alters on smaller tables and had to wait 10 minutes but I never got the `Error Code: 122 Lost connection to DDLProc` before. I did back up the server prior to doing this but would prefer to avoid a restore, which I've never performed before.

@davidhilldallas or @bhelm or anybody else, any ideas?

InfiniDB 4.6.7
2 node cluster in 'combined' mode

**Comment by sexygeoff** [comment]
Are there some clues in the logs below? Does InfiniDB make a copy of the table when performing the Alter Table? After the backup, my small disk is 80% full and I don't think there is room to create a copy of the table.
 
[root@infinidb bin]# tail -f /var/log/Calpont/crit.log
``` 
Apr 19 23:07:34 infinidb writeengine[29922]: 34.094583 |0|2593|0| C 19 CAL0080: Compression Handling: Compressed data does not fit, caused a chunk shifting @line:928 filename:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/005.dir/FILE000.cdf, chunkId:13 data size:2044201/available:0 -- shifting FAILED
Apr 19 23:07:34 infinidb writeengine[29922]: 34.094583 |0|2593|0| C 19 CAL0080: Compression Handling: Compressed data does not fit, caused a chunk shifting @line:928 filename:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/005.dir/FILE000.cdf, chunkId:13 data size:2044201/available:0 -- shifting FAILED
Apr 19 23:07:35 infinidb writeengine[29922]: 35.326304 |0|2593|0| C 19 CAL0080: Compression Handling: Compressed data does not fit, caused a chunk shifting @line:928 filename:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/005.dir/FILE002.cdf, chunkId:4 data size:2056168/available:0 -- shifting FAILED
Apr 19 23:07:35 infinidb writeengine[29922]: 35.326304 |0|2593|0| C 19 CAL0080: Compression Handling: Compressed data does not fit, caused a chunk shifting @line:928 filename:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/005.dir/FILE002.cdf, chunkId:4 data size:2056168/available:0 -- shifting FAILED
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110906 |0|2593|0| C 19 CAL0080: Compression Handling: Compressed data does not fit, caused a chunk shifting @line:928 filename:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf, chunkId:9 data size:2046452/available:0 -- shifting FAILED
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110906 |0|2593|0| C 19 CAL0080: Compression Handling: Compressed data does not fit, caused a chunk shifting @line:928 filename:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf, chunkId:9 data size:2046452/available:0 -- shifting FAILED
Apr 19 23:07:42 infinidb ProcessMonitor[28514]: 42.807300 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: WriteEngineServer, old PID = 29922
Apr 19 23:07:42 infinidb ProcessMonitor[28514]: 42.807300 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: WriteEngineServer, old PID = 29922
Apr 19 23:07:46 infinidb ProcessMonitor[28514]: 46.880394 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DDLProc, old PID = 30020
Apr 19 23:07:46 infinidb ProcessMonitor[28514]: 46.880394 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DDLProc, old PID = 30020
```
[root@infinidb bin]# tail -f /var/log/Calpont/err.log 
```
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110195 |0|2593|0| E 19 CAL0080: Compression Handling: Failed to uncompress chunk new /usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf@2134
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110330 |0|2593|0| E 19 CAL0080: Compression Handling: data file after chunk shifting failed verification.
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110330 |0|2593|0| E 19 CAL0080: Compression Handling: data file after chunk shifting failed verification.
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110398 |0|2593|0| E 19 CAL0080: Compression Handling: rename /usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf.orig to /usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf failed: No such file or directory
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110398 |0|2593|0| E 19 CAL0080: Compression Handling: rename /usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf.orig to /usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf failed: No such file or directory
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110613 |0|2593|0| E 19 CAL0080: Compression Handling: Chunk shifting failed, file:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf, rlc file is:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf.rlc.20160419230739110433, rlc file header in memory: /usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf.rlc.20160419230739110433.hdr
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110613 |0|2593|0| E 19 CAL0080: Compression Handling: Chunk shifting failed, file:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf, rlc file is:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf.rlc.20160419230739110433, rlc file header in memory: /usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf.rlc.20160419230739110433.hdr
Apr 19 23:07:39 infinidb writeengine[29922]: 39.110906 |0|2593|0| C 19 CAL0080: Compression Handling: Compressed data does not fit, caused a chunk shifting @line:928 filename:/usr/local/Calpont/data1/000.dir/000.dir/012.dir/098.dir/008.dir/FILE002.cdf, chunkId:9 data size:2046452/available:0 -- shifting FAILED
Apr 19 23:07:42 infinidb ProcessMonitor[28514]: 42.807300 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: WriteEngineServer, old PID = 29922
Apr 19 23:07:46 infinidb ProcessMonitor[28514]: 46.880394 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DDLProc, old PID = 30020
```

**Comment by davidhilldallas** [comment]
Looks like you ran into a BUG. The message "Lost connection to
DDLProc" usually means that the DDLProc crashes. You could check that by
viewing the /var/log/Calpont/crit.log.

You can check the other Calpont logs and see if anything else was reported
at the time of the crash., maybe a memory limit issue.

Also when it crashed, it would have left the table locked.

Now why it might have crashed, no clue there..

On Tue, Apr 19, 2016 at 4:26 PM, sexygeoff <notifications@github.com> wrote:

> Hi,
>
> I'm getting the following error when attempting to alter a table as
> follows: select calonlinealter("alter table table_name add column id
> bigint comment 'autoincrement,2147183537';");
>
> Error after just 10 seconds: Error Code: 122 Lost connection to DDLProc
>
> Output from ./viewtablelock:
>
> There is 1 table lock
>   Table         LockID  Process  PID    Session  Txn   CreationTime              State    DBRoots
>   bi.table_name  6       DDLProc  30020  14       2593  Tue Apr 19 23:07:29 2016  LOADING  1,2
>
> The table has 1.6 billion rows. The storage is local to each node and uses
> SSD drives. Do I just need to wait longer? How can I tell if anything is
> happening? I've made alters on smaller tables and had to wait 10 minutes
> but I never got the Error Code: 122 Lost connection to DDLProc before. I
> did back up the server prior to doing this but would prefer to avoid a
> restore, which I've never performed before.
>
> @davidhilldallas <https://github.com/davidhilldallas> or @bhelm
> <https://github.com/bhelm> or anybody else, any ideas?
>
> InfiniDB 4.6.7
> 2 node cluster in 'combined' mode
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/37>
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by sexygeoff** [comment]
@davidhilldallas I added the logs right before you answered. Are there any clues there? Does the table need to be copied to disk for the schema update and could missing disk space be the culprit?

**Comment by davidhilldallas** [comment]
Sorry, no answer for that one. Don't know if its trying to use temp disk space or memory while its doing the alter command. But it seems to be pointing that direction since it happened on a large table.

**Comment by sexygeoff** [comment]
I think the answer will be to just drop the ID column and live without it since it does't offer and real value in my use case. Not a good idea to use data type INT in a Big Data world, doh!

**Comment by bhelm** [comment]
i have'nt had to do alter tables often, but when i did it ended in a disaster :)

dropping the "failed" column indeed got my table back to a working state. if i really need to change the table structure i create a new one and INSERT INTO .. SELECT from the old.
as i often UPDATE my tables, this also has the advantage that the used disk space reduces by a factor of 5. afterwards, i swap the table names using a rename.

when talking about data types and big data, you should use UNSIGNED instead of SIGNED bigint whenever possible.

**Comment by sexygeoff** [comment]
I freed up disk space but was not able to perform the ALTER, same error. So I just dropped the column and things worked for a few minutes. But now I'm getting `Error Code: 122. The system is not yet ready to accept queries` constantly and need to restart InfiniDB in cmconsole. The crit.log shows this:

```
Apr 20 17:10:38 infinidb joblist[58460]: 38.998521 |0|0|0| C 05 CAL0000: distributedenginecomm.cpp @ 381 DEC: lost connection to 192.168.10.178
Apr 20 17:10:38 infinidb joblist[58460]: 38.998521 |0|0|0| C 05 CAL0000: distributedenginecomm.cpp @ 381 DEC: lost connection to 192.168.10.178
Apr 20 17:10:39 infinidb joblist[58240]: 39.040861 |0|0|0| C 05 CAL0000: distributedenginecomm.cpp @ 381 DEC: lost connection to 192.168.10.178
Apr 20 17:10:39 infinidb joblist[58240]: 39.040861 |0|0|0| C 05 CAL0000: distributedenginecomm.cpp @ 381 DEC: lost connection to 192.168.10.178
Apr 20 17:21:42 infinidb ProcessMonitor[102149]: 42.711823 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DBRMWorkerNode, old PID = 103037
Apr 20 17:21:42 infinidb ProcessMonitor[102149]: 42.711823 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DBRMWorkerNode, old PID = 103037
Apr 20 17:21:56 infinidb ProcessMonitor[102149]: 56.796737 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DBRMControllerNode, old PID = 102923
```

Is Calpont.xml supposed to be identical on my two servers? There are 2 differences. diff Calpont.xml.idb1 Calpont.xml.idb2:
```
22c22
< 		<ProcStatusControlStandby><IPAddr>0.0.0.0</IPAddr><Port>8605</Port></ProcStatusControlStandby>
---
> 		<ProcStatusControlStandby><IPAddr>192.168.10.178</IPAddr><Port>8605</Port></ProcStatusControlStandby>
220c220
< 		<StandbyOAMModuleName>unassigned</StandbyOAMModuleName>
---
> 		<StandbyOAMModuleName>pm2</StandbyOAMModuleName>
```

Could that be causing this sudden disconnect between nodes? @davidhilldallas, any thoughts on this new issue?

**Comment by davidhilldallas** [comment]
1. The Calpont.xml's should be the same. Might need to do a shutdown and
startsystem to get them back insync

2. But this difference would have anything to do with the alter failures
and it still looks like an outage is happening and leaving the system in a
bad state where you can't do other Db updates.. But still don't know why
the alter would be failing.

On Wed, Apr 20, 2016 at 10:56 AM, sexygeoff <notifications@github.com>
wrote:

> I freed up disk space but was not able to perform the ALTER, same error.
> So I just dropped the column and things worked for a few minutes. But now
> I'm getting Error Code: 122. The system is not yet ready to accept queries
> constantly and need to restart InfiniDB in cmconsole. The crit.log shows
> this:
>
> Apr 20 17:10:38 infinidb joblist[58460]: 38.998521 |0|0|0| C 05 CAL0000: distributedenginecomm.cpp @ 381 DEC: lost connection to 192.168.10.178
> Apr 20 17:10:38 infinidb joblist[58460]: 38.998521 |0|0|0| C 05 CAL0000: distributedenginecomm.cpp @ 381 DEC: lost connection to 192.168.10.178
> Apr 20 17:10:39 infinidb joblist[58240]: 39.040861 |0|0|0| C 05 CAL0000: distributedenginecomm.cpp @ 381 DEC: lost connection to 192.168.10.178
> Apr 20 17:10:39 infinidb joblist[58240]: 39.040861 |0|0|0| C 05 CAL0000: distributedenginecomm.cpp @ 381 DEC: lost connection to 192.168.10.178
> Apr 20 17:21:42 infinidb ProcessMonitor[102149]: 42.711823 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DBRMWorkerNode, old PID = 103037
> Apr 20 17:21:42 infinidb ProcessMonitor[102149]: 42.711823 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DBRMWorkerNode, old PID = 103037
> Apr 20 17:21:56 infinidb ProcessMonitor[102149]: 56.796737 |0|0|0| C 18 CAL0000: *****Calpont Process Restarting: DBRMControllerNode, old PID = 102923
>
> Is Calpont.xml supposed to be identical on my two servers? There are 2
> differences. diff Calpont.xml.idb1 Calpont.xml.idb2:
>
> 22c22
> <       <ProcStatusControlStandby><IPAddr>0.0.0.0</IPAddr><Port>8605</Port></ProcStatusControlStandby>
> ---
> >       <ProcStatusControlStandby><IPAddr>192.168.10.178</IPAddr><Port>8605</Port></ProcStatusControlStandby>
> 220c220
> <       <StandbyOAMModuleName>unassigned</StandbyOAMModuleName>
> ---
> >       <StandbyOAMModuleName>pm2</StandbyOAMModuleName>
>
> Could that be causing this sudden disconnect between nodes?
> @davidhilldallas <https://github.com/davidhilldallas>, any thoughts on
> this new issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/infinidb/infinidb/issues/37#issuecomment-212488421>
>



-- 
------------------
David Hill
InfiniDB Development/Customer Support
MariaDB Corporation
http://www.mariadb.com

**Comment by sexygeoff** [comment]
In the end I had to restore from backup to get the table working again. In the future I'll create tables with empty placeholder columns for possible expansion.

**Comment by brianrp** [comment]
We add and remove columns on an irregular basis, but have found it so reliable that it is automated. These are always int() columns.

My suggestions on this thread,  whenever you have a problem with InfiniDB, get back to a stable state, do a shutdownsystem and a startsystem to ensure every node is in sync with no errors in any of the logs and no tables are left locked.
Getting back to a stable state may be implementing the resolution to your problem or just backing out the change that was responsible.
Whichever you can get to first.

InfinDB may occasionally restart a process, usually this poses no problem and everything continues to work. With possibly a hiccup on what it was doing at the time. When this occurs check the Alarms and check the logs to ensure it did not switch to read-only mode or leave a table locked. If it did, then try to clear the lock and restartsystem.

As a dba, depending on your data and where you put temporary files, or allow the system to create temporary tables, don't ever let the disk get over 80% full. If it does, your top priority should be to get more space and resolve that issue as soon as possible. Always leave plenty of space for the system to create temporary files.

As an FYI- I never do a backup of the InfiniDB data, just the system schema. My ETL process can recreate any customer (schema) tables, and frequently does because one changed.  The files used to import data to the large tables become my (daily) data backup files.

Hope that helps.
