### ISSUE TITLE
HDFS implementation

### ISSUE THREAD

**Issue by ygwane** [infinidb/infinidb#4]
I'm trying to install infinidb over hdfs (HDP platform) but it seems to be not possible.
hdfsCheck binary is missing, also hdfs-12.so and hdfs-20.so are missing in sources.
If i take those files from latest archive released (4.6.0) and copies them into my compiled Calpont directory, i see this error :
ERROR: HDFS plugin not installed /usr/local/Calpont/lib/hdfs-20.so

**Comment by allanwax** [comment]
Try this `yum -y install hadoop-libhdfs.x86_64`
