### ISSUE TITLE
PrimProc could not open file

### ISSUE THREAD

**Issue by XtreamData** [infinidb/infinidb#40]
Hi all,
I get this error in the crit.log when loading data. Since we have hundreds of tables loading all the time I cannot isolate which table might cause the problem.

_PrimProc could not open file for OID 7855; /000.dir/000.dir/030.dir/175.dir/000.dir/FILE004.cdf:No such fi le or directory_

What might have caused this?
Is there a way I can isolate what table/tables is causing this?
How do I fix this?

Regards,
Frik

**Comment by dhall-InfiniDB** [comment]
if you do:
select tablename, columnname, objectid from calpontsys.syscolumn where objectid = 7855;

It will tell you which table and column that file belongs to.

There are two ways this error usually occurs. First, somehow that file was deleted. Second, the disk drive is full.

**Comment by XtreamData** [comment]
Thanks for the feedback. Deleted...? not us. Full drive... not possible
still have 300gb open.

Could this happen when there are not enough available inodes to open?
I checked the logs to find no error related to this.

**Comment by dhall-InfiniDB** [comment]
Not enough inodes, not enough file handles, these sorts of things, yes. I've run into file handle issues in another life. It takes a lot, generally, and columnstore by itself should never come close unless the machine is set up weird.

**Comment by bhelm** [comment]
you are not telling us, which infinidb version you are using. if you are on infinidb < 4.6.5 or < 4.6.6 (not sure which exact version), there was a bug that caused this error if there are queries executed on infinidb while the system is not fully initialized.
in this case, you should update to the latest infinidb version from mariadb (4.6.7 currently). The latest infinidb version will give an error like "Infinidb is not ready to accept queries" if there is a query when it is not fully up. 

if you are not planning to update, you can also block queries while infinidb is starting up using iptables on all nodes, for example:
``` /sbin/iptables -I INPUT -i eth0 -p tcp --destination-port 3306 -j REJECT```

**Comment by XtreamData** [comment]
We are using 4.6.7 from mariadb. We checked the inodes and file handles and it more than ample.
We requested reports from the SAN storage engineers. By miracle and a couple of restarts the problem went away and no data lost. Will keep you posted.
