### ISSUE TITLE
TPCH SQL #1 can not pass

### ISSUE THREAD

**Issue by tongsir** [infinidb/infinidb#46]
hi there
I'm running Infinidb 4.6 with 1UM and 4PMs, but I got problem that the first sql of TPCH test can not run normally, it returns error like below

> ERROR 122 (HY000): An unexpected condition within the query caused an internal processing error within InfiniDB. Please check the log files for more details. Additional Information: aggregation data overflow.

any suggestions ?

the TPCH query is below

> SELECT 
	L_RETURNFLAG,
	L_LINESTATUS,
	SUM(L_QUANTITY) AS SUM_QTY,
	SUM(L_EXTENDEDPRICE) AS SUM_BASE_PRICE,
	SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)) AS SUM_DISC_PRICE,
	SUM(L_EXTENDEDPRICE*(1-L_DISCOUNT)*(1+L_TAX)) AS SUM_CHARGE,
	AVG(L_QUANTITY) AS AVG_QTY,
	AVG(L_EXTENDEDPRICE) AS AVG_PRICE,
	AVG(L_DISCOUNT) AS AVG_DISC,
	COUNT(*) AS COUNT_ORDER
FROM 
	LINEITEM
WHERE 
	L_SHIPDATE <= date '1998-12-01' - interval '66' day
GROUP BY 
	L_RETURNFLAG,
	L_LINESTATUS
ORDER BY 
	L_RETURNFLAG,
	L_LINESTATUS;

**Comment by brianrp** [comment]
Check this variable:
show variables like 'max_length_for_sort_data';

In the my.cnf file you can set it to a higher value:
max_length_for_sort_data = 8388608
This is the max value for the setting.

**Comment by dhall-InfiniDB** [comment]
This may be related to <HashJoin><TotalUmMemory> in Calpont.xml. This value can be raised, but care must be taken not to cause too much memory paging. If this is a single server installation then <TotalUmMemory> and <DBBC><NumBlocksPct> draw from the same memory pool, as well as everything else.

**Comment by tongsir** [comment]
@brianrp @dhall-InfiniDB finally I got the solution

> mysql> set infinidb_use_decimal_scale = 1;
Query OK, 0 rows affected (0.00 sec)
mysql> set infinidb_decimal_scale=3;
Query OK, 0 rows affected (0.00 sec)

**Comment by brianrp** [comment]
Since your UM and PM's are on different machines, that setting only applies to the UM machine(s). It does not apply to PM's which do not run MySQL.
