### ISSUE TITLE
reclaim unused space. ?

### ISSUE THREAD

**Issue by a3plusb3** [infinidb/infinidb#51]
is there a function or tool that would allow me to reclaim unused space in the dbroots?

**Comment by bhelm** [comment]
see #38

**Comment by a3plusb3** [comment]
Hi Bhelm. 
Thanks 
I got another reason for the increased space usage from Dipti on Mariadb form. 
So the 8000000 rows space is preallocated 
so it means that when any space over the allocated is used then the entire space for the 8000000 rows is preallocated on the dbroot. 
hope this makes sense. 

my solution was to load anything less than a multiple of 8000000 on only that many dbroots.
