### ISSUE TITLE
infinidb filesystem management

### ISSUE THREAD

**Issue by calpont** [infinidb/infinidb#53]
InfiniDB being columnstore stores tables as columns. Columns are stored as files such as FILE000.cdf in cryptic directory structures.

I like to know if it is possible to manage the files such as compress etc. Is there a utility that does that?

**Comment by rdempseyidb** [comment]
I'm not sure I fully understand your question, but I suspect the answer is "no". Doing anything to those files outside of InfiniDB is likely to cause great harm to your database.

**Comment by bhelm** [comment]
Also, infinidb does compress the tables by default. It is possible to use any filesystem, even fuse bases encryption or compression wrappers, but this can cause table corruption in case of unexpected Server reboots. Not recommended.
