### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by DevLu** [infinidb/infinidb#6]
Been following the steps as described for building the binary trees.
It does not produce a "Calpont" directory as stated in the documentation.

My steps are as follows:
yum groupinstall "Development Tools" (installed)
yum install zlib-devel (installed)
yum install ncurses-devel (installed)
yum install libxml2-devel (installed)
yum install expect (installed)
yum install readline-devel (installed)
cd $HOME
mkdir infinidb-src
cd infinidb-src
wget -Omysql-4.6.2-1.tar.gz https://github.com/infinidb/mysql/archive/4.6.2-1.tar.gz
tar -zxf mysql-4.6.2-1.tar.gz
ln -s mysql-4.6.2-1 mysql
cd mysql
./configure --prefix=$HOME/infinidb/mysql
make
make install
cd ..
wget -Oinfinidb-4.6.2-1.tar.gz https://github.com/infinidb/infinidb/archive/4.6.2-1.tar.gz
tar -zxf infinidb-4.6.2-1.tar.gz
ln -s infinidb-4.6.2-1 infinidb
cd infinidb
./configure --prefix=$HOME/infinidb
make
make install

**Comment by bhelm** [comment]
just rename the directory to Calpont. then create a file releasenum in the Calpont directory and put this inside:
```
version=4.6.2
release=1

```
then 
```tar cfvz infinidb-4.6.2-1.x86_64.bin.tar.gz Calpont```

this will give you a ready-to-use binary tarball. extract it once within /usr/local/ so you have your installtion within /usr/local/Calpont
after that. you can run the /usr/local/Calpont/bin/postConfigure script. specify "binary" when asked for the installation type. the installer then will pick up the infinidb-4.6.2-1.x86_64.bin.tar.gz you have just created from your home dir.

i also had to create the file /etc/ld.so.conf.d/infinidb.conf
 ```
/usr/local/Calpont/lib                                                                                                                    
/usr/local/Calpont/mysql/lib/                                                                                                           
/usr/local/Calpont/mysql/lib/mysql/
```
then run ldconfig afterwards.

while installing, you may check the /tmp/pm* files for errors and /tmp/status.log for cluster status. for me, PM1 stayed in MAN_INIT status, rebooting all servers solved that for me.
also if you get errors when you issue your first create table statement (CAL0009: Error while calling getSysCatDBRoot), rerun the postConfigure script.

i hope that helps to get you started.

**Comment by DevLu** [comment]
Thanks bhelm,

When I run the /usr/local/Calpont/bin/postConfigure (it does start) I get a couple of errors:
-----------------------------------------------------------------------------------------------
/usr/local/Calpont/bin/getConfig: error while loading shared libraries: libjoblist.so.1: cannot open shared object file: No such file or directory
/usr/local/Calpont/bin/getConfig: error while loading shared libraries: libjoblist.so.1: cannot open shared object file: No such file or directory
[AND]
Running the Infinidb MySQL setup scripts
/root/bin/post-mysqld-install: line 31: cd: /root/mysql/lib/mysql: No such file or directory
/root/bin/post-mysqld-install: line 36: cd: /root/mysql/lib/mysql/plugin: No such file or directory
/root/bin/post-mysqld-install: line 70: /root/mysql/bin/mysql_install_db: No such file or directory
/root/bin/post-mysqld-install: line 95: cd: /root/mysql/lib/mysql/plugin: No such file or directory
cat: /usr/local/Calpont/mysql/db/*.pid: No such file or directory
ERROR: MySQL runtime error, exit...
sh: /root/mysql/bin/mysql: No such file or directory
---------------------------------------------------------------------------------------------------

Creating the /etc/ld.so.conf.d/infinidb.conf file:  Should I add those three paths to the file as I have 

Where is Idconfig file located? I can't find it. 

Let me know if you would like to look at my infinidb-4.6.2-1.x86_64.bin.tar.gz file. I can give you a download link.
Thank you sooooo much for your help.

**Comment by bhelm** [comment]
yes, the three paths need to get into the /etc/ld.so.conf.d/infinidb.conf file, 3 lines.

for the mysql install problem, i did not had this one. you may symlink /root/mysql to /usr/local/Calpont/mysql to work around it.

actually, if you just want to get started with infinidb rather than compiling it yourself, you should go to the mariadb download section and download it there. you need to remove the ldconfig stuff than, as these version does not require it and would throw conflicts if you still have it enabled.

also, you should use the .deb or .rpm version when possible. i had a lot of problems with my multi-node cluster as the install did never manage to start it with the binary distribution. the postconfigure needs to start and complete successfully. you may rerun it once.

**Comment by DevLu** [comment]
That's good to know about your struggles with the binary distro on a cluster.(That's what I'm trying to do as well.)
 
The reason why I'm trying to compile the latest version is because the rpm version(4.6.0-1 from MariaDB website) is:
a) not giving me the enterprise website. (ANY IDEAS)
b) I'm also not able to see the replication of new tables/data between UM and PMs. 
I'm trying to install it over three servers(multi-node). 
I don't know if it's my configuration or an issue with the platform. Do I need to manually symlink   
the data1/data2/..3/..4/..5/..6 directories on each of the PM's to point to the Directories on the UM?

My target configuration for my cluster is as follows(postConfigure I run on Server1):
Server1(UM1)(PM1), 192.168.30.11
Server2(PM2), 192.168.30.12
Server3(PM3)  192.168.30.13

* Select the type of System Server install [1=single, 2=multi] > 2 
* Installing on Amazon System (EC2 or VPC services) [y,n] > n
* Select the type of System Module Install [1=separate, 2=combined] > 2
* Enter System Name (calpont-1) > myinfinidb2
* Select the type of Data Storage [1=internal, 2=external] > 1

=============== Setup the Module Configuration ==============
----- Performance Module Configuration -----
* Enter number of Performance Modules [1,1024] (1) > 3
* Enter Starting Module ID for Performance Module [1,1022]  > 1

*** Parent OAM Module Performance Module #1 Configuration ***
* Enter Nic Interface #1 Host Name (unassigned) >Server1
* Enter Nic Interface #1 IP Address of Server1 (192.168.30.11) > 
* Enter Nic Interface #2 Host Name (unassigned) > 
* Enter the list (Nx,Ny,Nz) or range (Nx-Nz) of dbroot IDs assigned to module 'pm1' (1) > 1,2

*** Performance Module #2 Configuration ***
* Enter Nic Interface #1 Host Name (unassigned) > Server2
* Enter Nic Interface #1 IP Address of Server2 (192.168.30.12) > 
* Enter Nic Interface #2 Host Name (unassigned) > 
* Enter the list (Nx,Ny,Nz) or range (Nx-Nz) of dbroot IDs assigned to module 'pm2' () > 3,4

*** Performance Module #3 Configuration ***
* Enter Nic Interface #1 Host Name (unassigned) > Server3
* Enter Nic Interface #1 IP Address of Server3 (192.168.30.13) > 
* Enter Nic Interface #2 Host Name (unassigned) > 
* Enter the list (Nx,Ny,Nz) or range (Nx-Nz) of dbroot IDs assigned to module 'pm3' () > 5,6

===== InfiniDB SNMP-Trap Process Check  =====
* InfiniDB SNMP-Trap process is enabled, would you like to disable it [y,n]  > n

===== Setup the Network Management System (NMS) Server Configuration =====
This would be used to receive SNMP Traps from InfiniDB, like a Network Control Center
*Enter IP Address(es) of NMS Server (0.0.0.0) > 192.168.30.11

===== Setup the External Device Configuration =====
*Would you like to add an External Device? [y,n] > n

THANKS AGAIN!!

**Comment by davidhilldallas** [comment]
I can answer this question:

" a) not giving me the enterprise website. (ANY IDEAS)"

Here is the location to get additional information about Enterprise InfiniDB support from MariaDB:

    https://mariadb.com/services/infinidb-services

The Enterprise version of InfiniDB is now distributed and support by MariaDB since Oct 2014, when the company Calpont/InfiniDB went into Bankruptcy.

**Comment by bhelm** [comment]
you can try the 4.6.3 rpm from mariadb, its in the download section for registred users, create a free account. MariaDB also offers the latest documentation for download (on the right on the download page).

```My target configuration for my cluster is as follows(postConfigure I run on Server1):
Server1(UM1)(PM1), 192.168.30.11
Server2(PM2), 192.168.30.12
Server3(PM3) 192.168.30.13```
im not sure, if you choose the combined install, dont you have a UM on every node?

```b) I'm also not able to see the replication of new tables/data between UM and PMs. ```
the UM only uses the mysql directory to store schema informations. infinidb schema is stored in the infinidb mysql tables. the actual data is stored in the data* directories. if you import some MB of data into one table, you should see the data directories grow. also notice that data1/data2 is only on PM1, data3/4 only on PM2 and data5/6 only on PM3. thats normal, no need to symlink anything.

if you question is about how to syncronize multiple UM's, read the InfiniDBMultiUMGuide_4.6.3.pdf from the documentation.

also note that, using "internal" storage, you dont have a high availability setup. if one of you servers cashes unrecoverable, you will have to resetup you cluster from scatch, loosing all data.

**Comment by brianrp** [comment]
I am an InfiniDB user, not a developer. I never tried what you are proposing, a um with a pm on one machine and other pm on different machines. I don't think it is a good idea for a production setup. My interpretation is that 'consolidated' is both the pm and um on a single machine (i have done that), without additional pms. I have a cluster with several um's and several pm's.
The pm's will use a lot of system resources to answer queries quickly, this may have an impact on the um in your proposed setup if it gets busy. The data volumes are written to in distributed fashion. You won't see them grow at the same rate. Refer to the Concepts guide for details.

**Comment by DevLu** [comment]
Thanks bhelm/brianrp,

I've taken on board all your suggestions. 

I've now tried the the 4.6.3-1 installation, but I'm getting the following errors during the setup process. I'm positive that it's something small.
=======================Server layout=======================
UMServer(UM1)   192.168.30.11  (92)
PM1Server(PM1)   192.168.30.12   data1, data2  (90)
PM2Server(PM2)   192.168.30.13   data3, data4  (91)

====================pm2_rpm_install.log=====================
Copy InfiniDB OS files to Module                 
scp -r /usr/local/Calpont/local/etc  root@192.168.30.13:/usr/local/Calpont/local/.
/usr/local/Calpont/local/etc: No such file or directory
]0;root@UMServer:~ [root@UMServer ~]# DONE

Run Module Installer                       
scp /usr/local/Calpont/local/etc/pm2/*  root@192.168.30.13:/usr/local/Calpont/local/.
/usr/local/Calpont/local/etc/pm2/*: No such file or directory
]0;root@UMServer:~ [root@UMServer ~]# ERROR: File Not Found

====================um1_rpm_install.log======================
Copy InfiniDB OS files to Module                 
scp -r /usr/local/Calpont/local/etc  root@192.168.30.11:/usr/local/Calpont/local/.
/usr/local/Calpont/local/etc: No such file or directory
]0;root@UMServer:~ [root@UMServer ~]# ERROR

My setup options are as follows:
***********************************/usr/local/Calpont/bin/postConfigure***********************************
Select the type of System Server install [1=single, 2=multi] > 2
Installing on Amazon System (EC2 or VPC services) [y,n] > n
Select the type of System Module Install [1=separate, 2=combined] > 1
Enter System Name > myinfinidb2
Enter the Local Module Name or exit [pmx, exit] (pm1) > pm1
Select the type of Data Storage [1=internal, 2=external] > 2
Enter number of User Modules > 1 
Enter Starting Module ID for User Module > 1

*** User Module #1 Configuration ***
Enter Nic Interface #1 Host Name > UMServer
Enter Nic Interface #1 IP Address of UMServer > 192.168.30.11
Enter number of Performance Modules > 2
Enter Starting Module ID for Performance Module > 1

***Parent OAM Module Performance Module #1 Configuration *** 
Enter Nic Interface #1 Host Name > PM1Server
Enter Nic Interface #1 IP Address of PM1Server > 192.168.30.12
Enter the list of dbroot Ids assigned to module ‘pm1’ > 1,2

*** Performance Module #2 Configuration ***
Enter Nic Interface #1 Host Name > PM2Server
Enter Nic Interface #1 IP Address of PM2Server > 192.168.30.13
Enter the list of dbroot Ids assigned to module ‘pm1’ > 3,4

InfiniDB SNMP-Trap process is enabled, would you like to disable it [y,n] > n
Enter IP Address(es) of NMS Server (0.0.0.0) > 192.168.30.11

Would you like to add an External Device? [y,n] > n
Would you like to continue with the System Installation? [y, n] > y
Enter the Package Type being installed to other servers [rpm,deb,binary] > rpm
Enter password, hit ‘enter’ to default to using a ssh key, or ‘exit’ > ‘enter’

Thanks, a million

**Comment by bhelm** [comment]
``` Enter the Local Module Name or exit pmx, exit > pm1 ```
you are installing a seperate install, i think you should not type a local module name here. Try exit.

**Comment by bhelm** [comment]
just interested: what kind of external storage you are using?

**Comment by DevLu** [comment]
Thanks, I will try that in a second. I'm only using another server's storage area and mounting it. This will only be a trial installation setup before I do it on production.

I've tried a different approach where I've done the main installation from PM1. It got further where it installed and started up InfiniDB successfully on all 3 servers, but the setup failed on the following step: "InfiniDEB Database Platform Starting, please wait.........."

The message in the "/var/log/Calpont/debug.log" file is: 
Mar 12 11:34:17 CentOsUM01 ProcessManager[18537]: 17.198463 |0|0|0| D 17 CAL0000: Module ProcMon not active yet: pm2         
Mar 12 11:34:18 CentOsUM01 ProcessManager[18537]: 18.199282 |0|0|0| D 17 CAL0000: Set System State = 7         
Mar 12 11:34:18 CentOsUM01 ProcessMonitor[18455]: 18.199990 |0|0|0| D 18 CAL0000: statusControl: REQUEST RECEIVED: Set System State = FAILED         
Mar 12 11:34:18 CentOsUM01 ProcessManager[18537]: 18.202286 |0|0|0| D 17 CAL0000: startMgrProcessThread Exit - failure  

I will try your suggestion next, installing from PM1

**Comment by bhelm** [comment]
my suggestion is to do a seperate install from UM1 and leaving locale module empty when asked.

the "InfiniDEB Database Platform Starting, please wait.........." should only take some minutes. if its not up after, say, 20 minutes, it wont finish at all. You can start /usr/local/Calpont/bin/calpontConsole and type getSystemInfo to get a more detailed status. if this status is not changing for minutes, you can also abort the install, stop the infinidb service, kill all infinidb processes and run the install again, just confirming the settings from the last time. it will then reinstall everything and hopefully start this time.

**Comment by brianrp** [comment]
I was not aware you are trying to install in Amazon. If you want to make your life easier, refer to the InfiniDBInstallGuide_<version>.pdf.
See section 2.6 Preparing for Installation - Amazon Setup, and later under section 4.7 Installing and Configuring InfiniDB - Amazon Installation.
Even if you don't want to use that installation method, it may give you some insights.
I have not looked at the MariaDB documents yet, assuming they are still the same and the Amazon AMI is still available.
(It takes a while to run as it creates all the instances and storage for you.)

**Comment by brianrp** [comment]
Ps: If you use the AMI you may have to upgrade the installation to the latest version.

**Comment by DevLu** [comment]
brianrp - I'm not trying to install from Amazon.(n) 
I'm now using the latest InfiniDB version 4.6.3-1

I've finally got it working by selecting internal data storage. As soon as I choose external, it fails. 
I don't suspect this being a big problem as I can just mount the external storage media to the data1/data2/data3/data4 directories. Any thoughts on this?

Also, I've noticed that when I try and add an External Device to be monitored, the setup fails immediately giving me the following: "ERROR: Problem updating the InfiniDB System Configuration file."
Although when I run the postConfiguration again, I seems to have remembered my settings and to goes through. 

My only problem at this stage is that I can't get the Enterprise Management web-page to open in my browser. I assumed it is the "infinidb-enterprise-4.6.3-1.x86_64.rpm" that I must install. (In the documentation it refers to it as: infinidb-entmgr-release#.el6.x86_64.rpm)
Is this correct, or is it two different packages?

My postConfiguration that worked was:

Select the type of System Server install [1=single, 2=multi] (2) > 
Installing on Amazon System (EC2 or VPC services) [y,n] (n) > 
Select the type of System Module Install [1=separate, 2=combined] (1) > 
Enter System Name (myinfinidb) > 
Enter the Local Module Name or exit [pmx,exit] (pm1) > 
Select the type of Data Storage [1=internal, 2=external] (1) > 
Enter number of User Modules [1,1024] (1) > 
Enter Starting Module ID for User Module [1,1024] (1) > 
Enter Nic Interface #1 Host Name (UMServer) > 
Enter Nic Interface #1 IP Address of UMServer (192.168.30.11) > 
----- Performance Module Configuration -----
Enter number of Performance Modules [1,1024] (2) > 
Enter Starting Module ID for Performance Module [1,1023] (1) > 

*** Parent OAM Module Performance Module #1 Configuration ***
Enter Nic Interface #1 Host Name (PM1Server) > 
Enter Nic Interface #1 IP Address of PM1Server (192.168.30.12) > 
Enter the list (Nx,Ny,Nz) or range (Nx-Nz) of dbroot IDs assigned to module 'pm1' (1,2) > 

*** Performance Module #2 Configuration ***
Enter Nic Interface #1 Host Name (PM2Server) > 
Enter Nic Interface #1 IP Address of PM2Server (192.168.30.13) > 
Enter the list (Nx,Ny,Nz) or range (Nx-Nz) of dbroot IDs assigned to module 'pm2' (3,4) > 

InfiniDB SNMP-Trap process is enabled, would you like to disable it [y,n] (n) > 
Enter IP Address(es) of NMS Server (0.0.0.0) > 

Current List of External Devices being monitored

Device Name    IP Address
--------------------------    ----------------
StorageArray_86               192.168.30.86

Would you like to modify current list? [y,n] (n) > 
Would you like to add an External Device? [y,n] (n) > 


Hope someone will find this useful.

**Comment by bhelm** [comment]
you selections above are not visible. try quoting your text.

for external, mount /usr/local/Calpont/data1, mount /usr/local/Calpont/data2 and so on should work without any promt (not asking for password or something). infinidb keeps mounting them as needet from /etc/fstab.

i dont know anything about a enterprise website, nothing about it in the documentation. i dont think its in the enterprise package:
```
root@ns2343193:/home# dpkg --listfiles infinidb-enterprise 
/usr/local/Calpont/bin/oid2file
/usr/local/Calpont/bin/dbhealth.sql
/usr/local/Calpont/bin/glusterconf
/usr/local/Calpont/bin/dbhealth.sh
/usr/local/Calpont/bin/glusteradd
/usr/local/Calpont/bin/dumpobm
/usr/local/Calpont/bin/healthcheck
/usr/local/Calpont/bin/dumpcol
/usr/local/Calpont/bin/dumpVss
/usr/local/Calpont/bin/SesMgr
/usr/local/Calpont/bin/file2oid.pl
/usr/local/Calpont/bin/dbprof.pl
/usr/local/Calpont/bin/print_journal
/usr/local/Calpont/bin/displayJobGraph.sh
/usr/local/Calpont/bin/editTxn
/usr/local/Calpont/bin/glusterctl
/usr/local/Calpont/bin/databaseSizeReport
/usr/local/Calpont/bin/evalcol
/usr/local/Calpont/bin/redistributeDB
/usr/local/Calpont/bin/gdb
/usr/local/Calpont/tools
/usr/local/Calpont/tools/getsar.sh
/usr/local/Calpont/tools/getuserinput.sh
/usr/local/Calpont/tools/pscollect
/usr/local/Calpont/tools/prat
/usr/local/Calpont/tools/ps
/usr/local/Calpont/tools/getps.sh
/usr/local/Calpont/tools/tarfiles.sh
/usr/local/Calpont/tools/getmodules.sh
/usr/local/Calpont/tools/prat.sh
/usr/local/Calpont/tools/copy2here.sh
/usr/local/Calpont/tools/getlogs.sh
/usr/local/Calpont/tools/README
```

**Comment by brianrp** [comment]
Yes, it is a different package, or was in my version.
On my system:
$ rpm -qa | grep enterprise
infinidb-enterprise-<version>.x86_64
So the rpm was installed but the installation setup was never completed.

This document discusses system requirements, setup and installation, it refers to it as the 'Enterprise Manager package'.
InfiniDBEnterpriseManagerGuide_<version>.pdf (It was in the 4.6-1 documents package, haven’t looked at your document package)

Once installed it was intended to be on port 9090
http://<yourserver>:9090

However, It may not be part of the MariaDB software download, or may not be functional. I don't know where the developers left it when they turned it over to GitHub and MariaDB took on support.
It was in development in version 4.5. I had early access to it in 4.5.1. It isn't running/working in my 4.5.2, the service infinidb-em was not created.

If you have InfiniDB up and running, try to do all you administration from the cmconsole program on pm1. This will help keep the configuration files updated.

Note: I think the default installation is for charset latin1. If you want to change it to utf8 or something else, now it the time to do it. (before you start creating tables.)
InfiniDB can only handle 1 charset. Refer to the documentation, AdminGuide and SyntaxGuide.

**Comment by DevLu** [comment]
Guys, thank you soooo much for your help and tips! I really appreciate it. bhelm, I've updated my post to reflect my configurations.
