### ISSUE TITLE
InfiniDB for Apache Hadoop: Cannot start the system if adding pm2

### ISSUE THREAD

**Issue by thrieu** [infinidb/infinidb#8]
Hi,

I failed to add the second PM. Both of my 2 nodes are in the same intranet, and I stopped iptables service on both of them. When I tried to restart the system, the err.log is as the following:

Mar 12 09:57:07 yc02 controllernode[3503]: 07.059878 |0|0|0| E 29 CAL0000: DBRM: error: SessionManager::getSystemState() failed (network)

Or else if I tried to re-run postConfigure script:

Mar 12 10:35:41 yc02 oamcpp[2261]: 41.101283 |0|0|0| E 08 CAL0000: getSystemStatus: write exception: InetStreamSocket::connect: connect() error: Connection refused to: InetStreamSocket: sd: 227 inet: 192.168.11.102 port: 8604
Mar 12 10:35:41 yc02 oamcpp[2261]: 41.101381 |0|0|0| E 08 CAL0000: getSystemStatus: MessageQueueClient exception: API Failure return in getSystemStatus API
Mar 12 10:35:46 yc02 oamcpp[2261]: 46.102340 |0|0|0| E 08 CAL0000: getSystemStatus: write exception: InetStreamSocket::connect: connect() error: Connection refused to: InetStreamSocket: sd: 227 inet: 192.168.11.102 port: 8604
Mar 12 10:35:46 yc02 oamcpp[2261]: 46.102418 |0|0|0| E 08 CAL0000: getSystemStatus: MessageQueueClient exception: API Failure return in getSystemStatus API

There is the report generated by calpontSupport script in the attachment.

I am eagerly looking forward to hearing from you. Any answer is appreciated.

Thank you!

**Comment by DevLu** [comment]
Hi thrieu. Just a thought... Make sure your ssh service starts up automatically... and that all your servers can see each other using password-less ssh. Keep us updated on how you are getting on.

**Comment by thrieu** [comment]
Hi DevLu.
I confirmed again and it was okay for all nodes to login each other using password-less SSH.
Thanks for replying!
