### ISSUE TITLE
IDB-2003: Aggregation/Distinct memory limit is exceeded.

### ISSUE THREAD

**Issue by maxd** [infinidb/infinidb#9]
Hi All,

I forget how to fix:

```
IDB-2003: Aggregation/Distinct memory limit is exceeded.
```

Can anyone remember which settings of Calpont.xml should be increased?

**Comment by brianrp** [comment]
I have only ever had to adjust 2 things related to memory with InfiniDB.
In response to a query failure which pointed directly to this parameter.
In the my.cnf file:
max_length_for_sort_data= 8388608

It is a dynamic variable. So you can change it without a restart.

To adjust the size of memory consumed on the UM machines.
In the Calpont.XML
<TotalUmMemory>

Requires a shut down, change the variable and restart.

**Comment by maxd** [comment]
Thank you.
